#!/bin/bash

# Forex Trading Quick Reference
# Run this script to see all available forex commands

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "           FOREX TRADING - QUICK REFERENCE GUIDE"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "📋 AVAILABLE COMMANDS:"
echo ""
echo "1. Test Yahoo Finance API Connection:"
echo "   python test_yfinance.py"
echo ""
echo "2. Backtest Single Forex Pair:"
echo "   python backtest_forex.py EURUSD=X"
echo "   python backtest_forex.py GBPUSD=X"
echo "   python backtest_forex.py USDJPY=X"
echo ""
echo "3. Backtest All Major Pairs:"
echo "   python backtest_forex.py"
echo ""
echo "4. Custom Backtests:"
echo "   # 90 days, 4-hour candles"
echo "   python -c \"from backtest_forex import test_single_pair; test_single_pair('EURUSD=X', '90d', '4h')\""
echo ""
echo "   # 180 days, daily candles"
echo "   python -c \"from backtest_forex import test_single_pair; test_single_pair('GBPUSD=X', '180d', '1d')\""
echo ""
echo "   # 30 days, 15-minute candles"
echo "   python -c \"from backtest_forex import test_single_pair; test_single_pair('USDJPY=X', '30d', '15m')\""
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "           🌍 SUPPORTED FOREX PAIRS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Major Pairs:"
echo "  • EURUSD=X  (Euro / US Dollar)"
echo "  • GBPUSD=X  (British Pound / US Dollar)"
echo "  • USDJPY=X  (US Dollar / Japanese Yen)"
echo "  • AUDUSD=X  (Australian Dollar / US Dollar)"
echo "  • USDCAD=X  (US Dollar / Canadian Dollar)"
echo "  • NZDUSD=X  (New Zealand Dollar / US Dollar)"
echo "  • USDCHF=X  (US Dollar / Swiss Franc)"
echo ""
echo "Cross Pairs:"
echo "  • GBPJPY=X  (British Pound / Japanese Yen)"
echo "  • EURGBP=X  (Euro / British Pound)"
echo "  • EURJPY=X  (Euro / Japanese Yen)"
echo "  • AUDJPY=X  (Australian Dollar / Japanese Yen)"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "           ⏰ AVAILABLE TIMEFRAMES"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  • 1m, 5m, 15m, 30m  - Intraday trading"
echo "  • 1h, 4h            - Swing trading"
echo "  • 1d, 1wk, 1mo      - Position trading"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "           📊 LATEST BACKTEST RESULTS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Period: 30 days (Oct 6 - Nov 5, 2025)"
echo "Timeframe: 1-hour candles"
echo ""
echo "  Pair      | Trades | Win Rate | ROI    | Final Capital"
echo "  -------------------------------------------------------"
echo "  AUD/USD   |   1    |  0.00%   | -0.98% |    \$990.25"
echo "  EUR/USD   |   1    |  0.00%   | -2.02% |    \$979.82"
echo "  USD/JPY   |   2    | 50.00%   | -2.34% |    \$976.58"
echo "  GBP/USD   |   2    |  0.00%   | -2.91% |    \$970.89"
echo ""
echo "Note: Negative results due to ranging market conditions."
echo "Strategy performs best in trending markets."
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "           📚 DOCUMENTATION"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  • FOREX_TRADING.md - Complete forex trading guide"
echo "  • README.md        - Main project documentation"
echo "  • QUICKSTART.md    - Quick start guide"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
